### ISSUE TITLE
It seems I have discovered how to make Cat-Catch even more powerful, but what are the consequences of enabling this crucial option?

### ISSUE THREAD

**Issue by trimechee** [xifangczy/cat-catch#591]
Hi, I'm reading the documentation of cat-Catch and I discover an option that I saw in the settings but I didn't think it's a crucial option that can influence the media detection! :

Refresh, navigate to a new page, and clear the data captured by the current tab

I read the documentation: Refresh and navigate to a new page to clear the data captured by the current tag.
Divided into no cleaning, normal cleaning and frequent cleaning.

https://cat-catch.bmmmd.com/docs/settings#shua-xin-tiao-zhuan-dao-xin-ye-mian-qing-kong-dang-qian-biao-qian-zhua-qu-de-shu-ju

and it says: "If you encounter websites that cannot detect resources, first try changing the cleaning mode to normal or no cleaning."

so obviously I decide to activate the no-clean mode now to have a better chance of detecting certain complex media streams, so my question th great Mr @xifangczy :

if we activate the no-clean mode, what are the concrete consequences? I read the documentation but I didn't understand, sorry, if we activate the no-clean mode, the temporary data or video files will not be deleted? will it make surfing slower?

I don't care that web browsing becomes slower if this option is activated, what matters to me is being able to detect media links, in this case maybe it will be a good idea to add an option if we close the web browser, Cat-Catch will automatically delete all this data that could not be deleted since the no-clean mode is activated?

**Comment by xifangczy** [comment]
不会 如果你设置 不清理数据 不会有太大影响，标签关闭会进行自动清理，但不会随着页面刷新而清理，如果这个页面资源很多 你应该取消 排除重复的资源 这样可以避免查找重复导致的CPU占用。
注意的是 chrome给与扩展的临时储存只有 10MB (chrome 111版本以上)
https://developer.chrome.com/docs/extensions/reference/api/storage#storage_areas
超过10MB可能会引发一些错误。

If you set it to not clear data, it will not have a significant impact. Tags will be automatically cleared upon closing, but not with page refresh. If this page has many resources, you should deselect duplicate resources to avoid CPU usage caused by searching for duplicates.
Note that the temporary storage given by Chrome for extensions is only 10MB (Chrome version 111 and above)
https://developer.chrome.com/docs/extensions/reference/api/storage#storage_areas
Files larger than 10MB may cause some errors.

**Comment by trimechee** [comment]
Interesting and informative ! Thank's for these important explanations :) 💯
